name: On git push on :dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-18.04
    #runs-on: namgivu/ubuntu-pipenv:18.04-3.7  #TODO why this image not working while it available at https://hub.docker.com/r/namgivu/ubuntu-pipenv
    steps:
    - uses: actions/checkout@v1

    - name: Demo one-line script run
      run: echo 'This is branch :dev'

    - name: Demo multi-line script run
      run: |
        echo 'Line 00 from branch :dev'
        echo 'Line 01 from branch :dev'
        echo 'Line 02 from branch :dev'

    - name: notify actionstatus to slack channel
      uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          GITHUB_TOKEN: b1af639722c7f21089ae2176445410746c22357b # optional
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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 # required
        if: always() # Pick up events even if the job fails or is canceled.
